name: Update OpenSanctions Data

on:
  schedule:
    - cron: "0 2 * * *" # Runs every day at 2:00 AM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  process-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download and Process Data
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python -u scripts/update_sanctions.py

      - name: Upload Files to Cloudflare R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
        run: |
          aws s3 cp targets.simple.parquet s3://diliguard-sanctions-test/targets.simple.parquet --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
          aws s3 cp entities.ftm.parquet s3://diliguard-sanctions-test/entities.ftm.parquet --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
